Repository LingoBell/LingoBell-BackEnd, pull requests merged in 2024-07, with the labels that each got.

#40 create chatting room
  app/controllers/chat_controller.py
  app/controllers/user_controller.py
  app/database/chat.py
  app/database/follow.py
  app/database/user.py
  app/database/userlangs.py
  app/main.py
  app/routes/user_routes.py
  app/services/chat_service.py
  app/services/user_service.py
  requirements.txt
Labels: 🎈API, 💻Feature

#42 채팅 요청한 유저 목록 api 수정
  app/controllers/chat_controller.py
  app/controllers/user_controller.py
  app/main.py
  app/services/chat_service.py
  app/services/user_service.py
Labels: 🎈API, 🌀BugFix, 💻Feature

#41 Jay/transcription
  app/controllers/transcribe_controller.py
  app/database/follow.py
  app/database/user.py
  app/main.py
  app/routes/transcribe_routes.py
  app/services/transcribe_service.py
  requirements.txt
  temp.wav
  transcription.txt
Labels: 💻Feature, AI
