Repository LingoBell/LingoBell-BackEnd, pull requests merged in 2024-08, with the labels that each got.

#52 Update config for STT
  app/ai_recommendation/recommend_config.py
  app/controllers/chat_controller.py
  app/controllers/user_controller.py
  app/database/__init__.py
  app/database/aiquiz.py
  app/database/airecommend.py
  app/database/nation.py
  app/database/user.py
  app/main.py
  app/services/chat_service.py
  app/services/partners_service.py
  app/services/transcribe_service.py
  app/services/user_service.py
Labels: 💻Feature, AI

#55 Complete edit my page feature
  app/controllers/user_controller.py
  app/services/user_service.py
Labels: 💻Feature

#62 chatroomId string 으로 변경 후 난수로 생성 처리
  app/database/aiquiz.py
  app/database/airecommend.py
  app/database/chat.py
  app/database/chatmessage.py
  app/services/chat_service.py
  app/services/partners_service.py
Labels: 🎈API, 💻Feature, 🥝Refactor

#69 face api 삭제
  app/controllers/face_controller.py
  app/services/cha.png
  app/services/face_serveice.py
  checkpoints/controlnet/config.json
Labels: 🎈API, 🥝Refactor

#73 Receive STT from GPU server, translate according to users' language information dynamically
  app/controllers/chat_controller.py
  app/main.py
  app/services/transcribe_service.py
Labels: 🎈API, 💻Feature, AI

#74 Jay/Whisperstreaming
  app/controllers/chat_controller.py
  app/main.py
  app/services/transcribe_service.py
Labels: 🎈API, 💻Feature, AI

#78 stt + translation 기능 구현 완료
  app/services/transcribe_service.py
  app/voice_stream_ai/buffering_strategy/buffering_strategies.py
  app/voice_stream_ai/client.py
  app/voice_stream_ai/server.py
Labels: 🎈API, 💻Feature, AI

#81 fix hallucination
  app/voice_stream_ai/buffering_strategy/buffering_strategies.py
  app/voice_stream_ai/server.py
  audio_files/0c4ad9fc-1333-4852-bf91-82f147aa1e05_6.wav
Labels: 🌀BugFix, AI
